In [6]:
import os
from pathlib import Path
from pprint import pprint
import numpy as np
import pandas as pd

def download_file_from_gdrive(file_url, filename, out_path: Path, overwrite=False):
    """
    Downloads a file from GDrive given an URL
    :param file_url: a string formated as https://drive.google.com/uc?id=<file_id>
    :param: the desired file name
    :param: the desired folder where the file will be downloaded to
    :param overwrite: whether to overwrite the file if it already exists
    """
    file_exists = os.path.exists(f'{out_path}/{filename}')

    if (file_exists and overwrite) or (not file_exists):
        os.system(f'gdown {file_url} -O {out_path}/{filename}')

In [11]:
FILE_URL = "https://drive.google.com/uc?id=1N8eav5HWd6A7rG0ZCRo7rNFryqZS4tVg"
FILE_NAME = "train.json"
DATA_PATH = Path("/Users/nikolaj/Desktop/DataScince/ODS")

In [12]:
df = pd.read_json(DATA_PATH / FILE_NAME,
                  convert_dates=['created'])

In [13]:
df.head()

bathrooms  bedrooms                       building_id             created  \
4         1.0         1  8579a0b0d54db803821a35a4a615e97a 2016-06-16 05:55:27   
6         1.0         2  b8e75fc949a6cd8225b455648a951712 2016-06-01 05:44:33   
9         1.0         2  cd759a988b8f23924b5a2058d5ab2b49 2016-06-14 15:19:59   
10        1.5         3  53a5b119ba8f7b61d4e010512e0dfc85 2016-06-24 07:54:24   
15        1.0         0  bfb9405149bfff42a92980b594c28234 2016-06-28 03:50:23   

                                          description      display_address  \
4   Spacious 1 Bedroom 1 Bathroom in Williamsburg!...  145 Borinquen Place   
6   BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...            East 44th   
9   **FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...     East 56th Street   
10  A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...  Metropolitan Avenue   
15  Over-sized Studio w abundant closets. Availabl...     East 34th Street   

                                             features  latitude  listing_id  \
4   [Dining Room, Pre-War, Laundry in Building, Di...   40.7108     7170325   
6   [Doorman, Elevator, Laundry in Building, Dishw...   40.7513     7092344   
9   [Doorman, Elevator, Laundry in Building, Laund...   40.7575     7158677   
10                                                 []   40.7145     7211212   
15  [Doorman, Elevator, Fitness Center, Laundry in...   40.7439     7225292   

    longitude                        manager_id  \
4    -73.9539  a10db4590843d78c784171a107bdacb4   
6    -73.9722  955db33477af4f40004820b4aed804a0   
9    -73.9625  c8b10a317b766204f08e613cef4ce7a0   
10   -73.9425  5ba989232d0489da1b5f2c45f6688adc   
15   -73.9743  2c3b41f588fbb5234d8a1e885a436cfa   

                                               photos  price  \
4   [https://photos.renthop.com/2/7170325_3bb5ac84...   2400   
6   [https://photos.renthop.com/2/7092344_7663c19a...   3800   
9   [https://photos.renthop.com/2/7158677_c897a134...   3495   
10  [https://photos.renthop.com/2/7211212_1ed4542e...   3000   
15  [https://photos.renthop.com/2/7225292_901f1984...   2795   

             street_address interest_level  
4       145 Borinquen Place         medium  
6             230 East 44th            low  
9      405 East 56th Street         medium  
10  792 Metropolitan Avenue         medium  
15     340 East 34th Street            low

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(1, 1))
vect.fit_transform(["no i have cows", "i have no cows"]).toarray(), vect.vocabulary_

(array([[1, 1, 1],
        [1, 1, 1]]),
 {'no': 2, 'have': 1, 'cows': 0})

In [23]:
vect = CountVectorizer(ngram_range=(1, 2))
vect.fit_transform(["no i have cows", "i have no cows"]).toarray(), vect.vocabulary_

(array([[1, 1, 1, 0, 1, 0, 1],
        [1, 1, 0, 1, 1, 1, 0]]),
 {'no': 4,
  'have': 1,
  'cows': 0,
  'no have': 6,
  'have cows': 2,
  'have no': 3,
  'no cows': 5})

In [ ]:
from scipy.spatial.distance import euclidean
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(ngram_range=(3, 3), analyzer="char_wb")

n1, n2, n3, n4 = vect.fit_transform(
    ["andersen", "petersen", "petrov", "smith"]
).toarray()

euclidean(n1, n2), euclidean(n2, n3), euclidean(n3, n4)

## Feature transformations

### Normalization and changing distribution

In [24]:
import numpy as np
from scipy.stats import beta, shapiro
from sklearn.preprocessing import StandardScaler

data = beta(1, 10).rvs(1000).reshape(-1, 1)
shapiro(data)

ShapiroResult(statistic=np.float64(0.8535712323007012), pvalue=np.float64(1.8779479698665446e-29))

In [28]:
data = np.array([1, 1, 0, -1, 2, 1, 2, 3, -2, 4, 100]).reshape(-1, 1).astype(np.float64)
StandardScaler().fit_transform(data)

array([[-0.31922662],
       [-0.31922662],
       [-0.35434155],
       [-0.38945648],
       [-0.28411169],
       [-0.31922662],
       [-0.28411169],
       [-0.24899676],
       [-0.42457141],
       [-0.21388184],
       [ 3.15715128]])

In [29]:
(data - data.mean()) / data.std()

array([[-0.31922662],
       [-0.31922662],
       [-0.35434155],
       [-0.38945648],
       [-0.28411169],
       [-0.31922662],
       [-0.28411169],
       [-0.24899676],
       [-0.42457141],
       [-0.21388184],
       [ 3.15715128]])

In [30]:
from sklearn.preprocessing import MinMaxScaler

MinMaxScaler().fit_transform(data)

array([[0.02941176],
       [0.02941176],
       [0.01960784],
       [0.00980392],
       [0.03921569],
       [0.02941176],
       [0.03921569],
       [0.04901961],
       [0.        ],
       [0.05882353],
       [1.        ]])

In [33]:
# Synthetic example

from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression

logit = LogisticRegression(solver="lbfgs", random_state=17)

x_data_generated, y_data_generated = make_classification()

rf = RandomForestClassifier(n_estimators=10, random_state=17)
pipe = make_pipeline(SelectFromModel(estimator=rf), logit)

print(
    cross_val_score(
        logit, x_data_generated, y_data_generated, scoring="neg_log_loss", cv=5
    ).mean()
)
print(
    cross_val_score(
        rf, x_data_generated, y_data_generated, scoring="neg_log_loss", cv=5
    ).mean()
)
print(
    cross_val_score(
        pipe, x_data_generated, y_data_generated, scoring="neg_log_loss", cv=5
    ).mean()
)

-0.3412791106327758
-0.4267475299690961
-0.3381039502140517


In [34]:
# x_data, y_data = get_data()
x_data = x_data_generated
y_data = y_data_generated

pipe1 = make_pipeline(StandardScaler(), SelectFromModel(estimator=rf), logit)

pipe2 = make_pipeline(StandardScaler(), logit)

print(
    "LR + selection: ",
    cross_val_score(pipe1, x_data, y_data, scoring="neg_log_loss", cv=5).mean(),
)
print(
    "LR: ", cross_val_score(pipe2, x_data, y_data, scoring="neg_log_loss", cv=5).mean()
)
print("RF: ", cross_val_score(rf, x_data, y_data, scoring="neg_log_loss", cv=5).mean())

LR + selection:  -0.34060055991938876
LR:  -0.34748392382242244
RF:  -0.4267475299690961


In [ ]:
# Install mlxtend
from mlxtend.feature_selection import SequentialFeatureSelector

selector = SequentialFeatureSelector(
    logit, scoring="neg_log_loss", verbose=2, k_features=3, forward=False, n_jobs=-1
)

selector.fit(x_data, y_data)